import 'dotenv/config'
export const ENV={
PORT:process.env.PORT,
MONGO_URL:process.env.MONGO_URL,
// GT9lwiSjurAJ4jkg,
NODE_ENV:process.env.NODE_ENV,
JWT_SECRET:process.env.JWT_SECRET,
RESEND_API_KEY:process.env.RESEND_API_KEY,
EMAIL_FROM:process.env.EMAIL_FROM,
EMAIL_FROM_NAME:process.env.EMAIL_FROM_NAME,
CLIENT_URL:process.env.CLIENT_URL,
CLOUDINARY_CLOUD_NAME:process.CLOUDINARY_CLOUD_NAME,
CLOUDINARY_API_KEY:process.CLOUDINARY_API_KEY,
CLOUDINARY_API_SECRET:process.CLOUDINARY_API_SECRET
}